<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickChargeAmount</name>
   <tag></tag>
   <elementGuidId>e5cff53c-246b-4250-9ce9-bef927ecec4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/input[@id='_id3:EditEventChargeWP_ChargeAmountsP_ScheduleMoneyP_ctlAmount']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
