<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickEdit</name>
   <tag></tag>
   <elementGuidId>89434568-24e7-43b1-8537-92fe5824d92e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/button[text()='Edit...']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
