<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickNew</name>
   <tag></tag>
   <elementGuidId>2620cdca-8fa1-47af-bc09-e723bab3f8df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/button[@value='New...']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
