<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>application</name>
   <tag></tag>
   <elementGuidId>1e0b6db6-72c0-4a8b-90c0-7f2da6730686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th/div[text()='Application']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
