<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>charge</name>
   <tag></tag>
   <elementGuidId>36a677fe-9838-4022-a0d3-555963e19c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/h4/a[@id='ChargesSummaryWP_OurChargesP_MasterChargesSummary_ctlArgTitle_title']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
